export let initialItems = [
    {text: "The Earth is the only planet in our solar system known to support life.", type: "fact"},
    {text: "Chocolate comes from a bean.", type: "fact"},
    {text: "The population of the world is over 10 billion people.", type: "false"},
    {text: "The Great Wall of China is visible from the moon with the naked eye.", type: "false"},
    {text: "A group of owls is called a parliament.", type: "fact"},
    {text: "Diamonds are the hardest natural substance on Earth.", type: "fact"},
    {text: "The human brain never stops growing.", type: "false"},
    {text: "The national animal of the United States is the bald eagle.", type: "fact"},
    {text: "The world's oceans contain more salt than all the salt mines on Earth combined.", type: "fact"},
    {text: "There are more stars in the universe than grains of sand on all the beaches on Earth.", type: "fact"},
    {text: "Snakes have eyelids.", type: "fact"},
    {text: "Bulls are attracted to the color red.", type: "false"},
    {text: "The world is flat.", type: "false"},
    {text: "The kangaroo is the only mammal that can hop.", type: "fact"},
    {text: "Ostriches bury their heads in the sand when they are scared.", type: "false"},
    {text: "Lightning can strike the same place twice.", type: "fact"},
    {text: "You can taste with your whole tongue.", type: "false"},
    {text: "The saying 'an apple a day keeps the doctor away' is a scientifically proven fact.", type: "false"},
    {text: "Sharks never stop swimming or they will die.", type: "false"},
    {text: "The population of the Earth is made up of mostly water.", type: "fact"},
    {text: "The number 8 is considered lucky in China.", type: "fact"},
    {text: "The Mona Lisa was painted by Leonardo da Vinci.", type: "fact"},
    {text: "The capital of Australia is Sydney.", type: "false"},
    {text: "The Internet was invented by a single person.", type: "false"},
    {text: "There are more muscles in your eyes than anywhere else in your body.", type: "fact"}
    // Add more facts and jokes here
];