import {QuestionType} from "../FactOrFalseChoose.tsx";

export let initialItemsEasy: QuestionType[] = [
    {text: "The Earth is the only planet in our solar system known to support life.", type: "fact"},
    {text: "Chocolate comes from a bean.", type: "fact"},
    {text: "The sun is a star.", type: "fact"},
    {text: "The moon is made of cheese.", type: "false"},
    {text: "There are seven continents on Earth.", type: "fact"},
    {text: "Elephants are the smallest mammal.", type: "false"},
    {text: "Mount Everest is the tallest mountain in the world.", type: "fact"},
    {text: "The Great Wall of China is visible from space.", type: "false"},
    {text: "Dogs are herbivores.", type: "false"},
    {text: "A tomato is a vegetable.", type: "false"},
    {text: "The Eiffel Tower is in London.", type: "false"},
    {text: "The human body has four lungs.", type: "false"},
    {text: "Fish can blink.", type: "false"},
    {text: "Bats are blind.", type: "false"},
    {text: "The capital of Australia is Sydney.", type: "false"},
    {text: "Polar bears have white skin.", type: "false"},
    {text: "Penguins are found in the Arctic.", type: "false"},
    {text: "The Sahara is the largest desert in the world.", type: "fact"},
    {text: "The Nile is the longest river in the world.", type: "fact"},
    {text: "Kangaroos are native to North America.", type: "false"},
    {text: "The human skeleton is made up of less than 100 bones.", type: "false"},
    {text: "Bananas grow on trees.", type: "false"},
    {text: "The Pacific Ocean is the largest ocean on Earth.", type: "fact"},
    {text: "Venus is the closest planet to the Sun.", type: "false"},
    {text: "An octopus has three hearts.", type: "fact"},
];
