import {QuestionType} from "../FactOrFalseChoose.tsx";

export let initialItemsScience: QuestionType[] = [
    {text: "Water boils at 100 degrees Celsius at sea level.", type: "fact"},
    {text: "The chemical symbol for Oxygen is O.", type: "fact"},
    {text: "The human body has 206 bones.", type: "fact"},
    {text: "Photosynthesis is the process plants use to produce food.", type: "fact"},
    {text: "The Earth revolves around the Sun in approximately 365.25 days.", type: "fact"},
    {text: "The speed of light is approximately 299,792 kilometers per second.", type: "fact"},
    {text: "The atomic number of hydrogen is 1.", type: "fact"},
    {text: "The DNA molecule is a double helix structure.", type: "fact"},
    {text: "The three states of matter are solid, liquid, and gas.", type: "fact"},
    {text: "The largest planet in our solar system is Jupiter.", type: "fact"},
    {text: "The chemical symbol for gold is Au.", type: "fact"},
    {text: "Sound travels faster in water than in air.", type: "fact"},
    {text: "The human body is made up of approximately 70% water.", type: "fact"},
    {text: "The first law of thermodynamics is the law of conservation of energy.", type: "fact"},
    {text: "The powerhouse of the cell is the mitochondria.", type: "fact"},
    {text: "The universal gravitational constant is denoted by the letter G.", type: "fact"},
    {text: "The chemical symbol for Iron is Fe.", type: "fact"},
    {text: "The Earth's atmosphere is primarily composed of nitrogen.", type: "fact"},
    {text: "The boiling point of water at sea level is 100 degrees Celsius.", type: "fact"},
    {text: "The largest moon in the solar system is Ganymede.", type: "fact"},
    {text: "The first World War ended in 1918.", type: "fact"},
    {text: "The atomic number of hydrogen is 2.", type: "false"},
    {text: "The human body contains 24 ribs.", type: "fact"},
    {text: "The three primary colors are red, blue, and green.", type: "false"},
    {text: "The speed of sound is faster than the speed of light.", type: "false"},
];