import {QuestionType} from "../FactOrFalseChoose.tsx";

export let initialItemsHistory: QuestionType[] = [
    {text: "The American Civil War ended in 1865.", type: "fact"},
    {text: "World War II started in 1930.", type: "false"},
    {text: "The Great Fire of London occurred in 1666.", type: "fact"},
    {text: "Julius Caesar was the first Roman Emperor.", type: "false"},
    {text: "The Magna Carta was signed in 1215.", type: "fact"},
    {text: "The Titanic sank in 1911.", type: "false"},
    {text: "Martin Luther King Jr. delivered his 'I Have a Dream' speech in 1963.", type: "fact"},
    {text: "The French Revolution started in 1789.", type: "fact"},
    {text: "Christopher Columbus discovered America in 1492.", type: "fact"},
    {text: "The first man to walk on the moon was Neil Armstrong in 1969.", type: "fact"},
    {text: "The Berlin Wall fell in 1980.", type: "false"},
    {text: "The Hundred Years' War lasted 100 years.", type: "false"},
    {text: "The Declaration of Independence was signed in 1776.", type: "fact"},
    {text: "The first World War ended in 1918.", type: "fact"},
    {text: "The atomic bomb was dropped on Hiroshima in 1944.", type: "false"},
    {text: "Napoleon Bonaparte was a French military leader in the 1800s.", type: "fact"},
    {text: "The Battle of Hastings took place in 1066.", type: "fact"},
    {text: "The Roman Empire fell in 476 AD.", type: "fact"},
    {text: "The Industrial Revolution began in the late 1700s.", type: "fact"},
    {text: "The United States was founded in 1776.", type: "fact"},
    {text: "The Great Depression began in 1929.", type: "fact"},
    {text: "The Renaissance began in the 14th century.", type: "fact"},
    {text: "The first successful airplane flight by the Wright Brothers was in 1903.", type: "fact"},
    {text: "The Vietnam War ended in 1975.", type: "fact"},
    {text: "The Russian Revolution took place in 1917.", type: "fact"},
];