import {QuestionType} from "../FactOrFalseChoose.tsx";

export let initialItemsExpert: QuestionType[] = [
    {text: "The sum of all interior angles of any polygon is 180 degrees.", type: "false"},
    {text: "The derivative of a constant is always zero.", type: "fact"},
    {text: "The capital of Bhutan is Thimphu.", type: "fact"},
    {text: "The chemical symbol for Tin is Tn.", type: "false"},
    {text: "The Battle of Waterloo ended the Hundred Years' War.", type: "false"},
    {text: "The speed of sound in air at sea level is approximately 343 meters per second.", type: "fact"},
    {text: "The human body has 206 bones.", type: "fact"},
    {text: "The chemical symbol for Iron is Fe.", type: "fact"},
    {text: "The universe is approximately 14.8 billion years old.", type: "false"},
    {text: "The Great Pyramid of Giza was built by Cleopatra.", type: "false"},
    {text: "The Mariana Trench is the highest point in the world's mountains.", type: "false"},
    {text: "The currency of Brazil is the Real.", type: "fact"},
    {text: "The largest moon in the solar system is Titan.", type: "false"},
    {text: "The first World War ended in 1919.", type: "false"},
    {text: "The atomic number of hydrogen is 1.", type: "fact"},
    {text: "The human body contains 12 ribs.", type: "false"},
    {text: "The three primary colors are red, blue, and yellow.", type: "fact"},
    {text: "The Earth's atmosphere is primarily composed of oxygen.", type: "false"},
    {text: "The boiling point of water at sea level is 100 degrees Fahrenheit.", type: "false"},
    {text: "The currency of Japan is the Yen.", type: "fact"},
    {text: "The largest planet in the solar system is Saturn.", type: "false"},
    {text: "The capital of Spain is Madrid.", type: "fact"},
    {text: "The chemical symbol for gold is Au.", type: "fact"},
    {text: "The longest river in the world is the Nile River.", type: "fact"},
    {text: "The speed of sound is slower than the speed of light.", type: "fact"},
];