import {QuestionType} from "../FactOrFalseChoose.tsx";

export let initialItemsGeography: QuestionType[] = [
    {text: "The capital of France is Paris.", type: "fact"},
    {text: "The Nile is the longest river in the United States.", type: "false"},
    {text: "Mount Everest is located in Nepal.", type: "fact"},
    {text: "Australia is the smallest continent.", type: "fact"},
    {text: "The Sahara Desert is located in Australia.", type: "false"},
    {text: "The Amazon Rainforest is located in Africa.", type: "false"},
    {text: "The Great Barrier Reef is off the coast of Australia.", type: "fact"},
    {text: "The capital of Canada is Vancouver.", type: "false"},
    {text: "Antarctica is the coldest continent on Earth.", type: "fact"},
    {text: "The Indian Ocean is the largest ocean on Earth.", type: "false"},
    {text: "The Rocky Mountains are located in the United States.", type: "fact"},
    {text: "The capital of Japan is Beijing.", type: "false"},
    {text: "The River Thames is located in London.", type: "fact"},
    {text: "The Andes are the longest mountain range in the world.", type: "fact"},
    {text: "The Suez Canal connects the Mediterranean Sea and the Red Sea.", type: "fact"},
    {text: "The capital of Australia is Sydney.", type: "false"},
    {text: "The Dead Sea is the lowest point on Earth's surface.", type: "fact"},
    {text: "The Amazon River is in Asia.", type: "false"},
    {text: "The Gobi Desert is in Africa.", type: "false"},
    {text: "The capital of Italy is Rome.", type: "fact"},
    {text: "The Great Wall of China is visible from space.", type: "false"},
    {text: "The Atlantic Ocean is the smallest ocean on Earth.", type: "false"},
    {text: "The capital of Russia is Moscow.", type: "fact"},
    {text: "The highest waterfall in the world is Angel Falls in Venezuela.", type: "fact"},
    {text: "The equator passes through Australia.", type: "false"},
];