import {QuestionType} from "../FactOrFalseChoose.tsx";

export let initialItemsHard: QuestionType[] = [
    {text: "Quantum mechanics is a branch of chemistry.", type: "false"},
    {text: "The square root of -1 is an imaginary number.", type: "fact"},
    {text: "The capital of Canada is Toronto.", type: "false"},
    {text: "The Pythagorean theorem applies only to right-angled triangles.", type: "fact"},
    {text: "The Mona Lisa was painted by Michelangelo.", type: "false"},
    {text: "The speed of light is approximately 299,792 kilometers per second.", type: "fact"},
    {text: "The human body has 205 bones.", type: "false"},
    {text: "The chemical symbol for Iron is Ir.", type: "false"},
    {text: "The universe is approximately 13.8 billion years old.", type: "fact"},
    {text: "The Great Pyramid of Giza was built by Alexander the Great.", type: "false"},
    {text: "The Mariana Trench is the deepest point in the world's oceans.", type: "fact"},
    {text: "The currency of Brazil is the Dollar.", type: "false"},
    {text: "The largest moon in the solar system is Ganymede.", type: "fact"},
    {text: "The first World War ended in 1918.", type: "fact"},
    {text: "The atomic number of hydrogen is 2.", type: "false"},
    {text: "The human body contains 24 ribs.", type: "fact"},
    {text: "The three primary colors are red, blue, and green.", type: "false"},
    {text: "The Earth's atmosphere is primarily composed of nitrogen.", type: "fact"},
    {text: "The boiling point of water at sea level is 100 degrees Celsius.", type: "fact"},
    {text: "The currency of Japan is the Yuan.", type: "false"},
    {text: "The largest planet in the solar system is Jupiter.", type: "fact"},
    {text: "The capital of Spain is Barcelona.", type: "false"},
    {text: "The chemical symbol for gold is Gd.", type: "false"},
    {text: "The longest river in the world is the Amazon River.", type: "false"},
    {text: "The speed of sound is faster than the speed of light.", type: "false"},
];